#http://docs.travis-ci.com/user/languages/android/
sudo: false
language: android

jdk:
  #- oraclejdk8
  - oraclejdk7
  #- openjdk7
  #- openjdk6
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
#ant deps

# use android:components:xxx instead.
#    - android-update-sdk --components=android-23
#    - android-update-sdk --components=build-tools-23.0.1
#    - android-update-sdk --components=extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
#  - cat `which android-wait-for-emulator`
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &


script:
# aD first & install second.
  - ./gradlew assembleDebug
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb devices
  - ./gradlew cAT
#  - adb logcat -d
  
#  - adb shell monkey -p org.bangbang.song.android.commonlib.demo -v 9999

